linters:
  enable:
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gocritic
    - gofumpt
    - gomnd
    - gomoddirectives
    - ifshort
    - importas
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    #- paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - thelper
    - unconvert
    - wastedassign
    - whitespace
    - wsl
linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-functions: strconv.*
  tagliatelle:
    case:
      rules:
        json: snake
issues:
  exclude:
    - Magic number
